#!/usr/bin/python


import unittest

from exercises.chap0 import q0000


class TestCase(unittest.TestCase):
    def test_docstring(self):
        self.assertIsNotNone(q0000.foo.__doc__)


if __name__ == '__main__':
    unittest.main()
